### ISSUE TITLE
Option to configure order reference

### ISSUE THREAD

**Issue by andykearney** [white-nl/commerce-sendcloud#1]
Hi!

We have a multi site setup that I'm trying to configure the shipping rules for. It's 3 brands in the same database. 

We use a simple rule to prefix the craft order reference with a letter to give easy visibility as to which site an order belongs to. When configuring Sendcloud a simple shipping rule  based on the letter the order reference is prefixed with can be used to set the brand and ship from preferences in order to determine label and email branding etc

However, Sendcloud is currently receiving the 6 digit craft order ID so no relevant rules are configurable. Is there any possibility of allowing the reference that sendcloud receives to be configurable in the plugin settings?

**Comment by WHITE-developer** [comment]
Hi @andykearney 

Sorry for the delay in answering.
Right now this isn't possible. We are in close contact to check if we can build this, so to be continued.

The plugin is designed to work completely from within Craft. If you map the Sendcloud shipping names exactly with a Craft shipping method as described [in our docs under Basic Setup](https://white.nl/en/craft-plugins/sendcloud/docs/) then you can use the "Push to Sendcloud" and "Print Label" buttons to handle your orders.

**Comment by bleepsandblops** [comment]
Would love the simple version of that which is being able to define which order field gets used as the reference number.

**Comment by WHITE-developer** [comment]
Just release a new version, where it is possible to configure the order number in the settings
