### ISSUE TITLE
house_number is required for some countries but the plugin is sending addressLine2 (which is sometimes empty and not usually a house number)

### ISSUE THREAD

**Issue by bleepsandblops** [white-nl/commerce-sendcloud#16]
### Description
This line is sending the addressLine2 field instead of the Sendcloud 'house_number' 
https://github.com/white-nl/commerce-sendcloud/blob/71754d24f57162d732c0c1ab30af05bebc4f3247/src/client/JouwWebSendcloudAdapter.php#L245C32-L245C32

Problem is on some countries (Switzerland is where I got the bug but there may be more), that field is required. So if the line 2 is empty, we're getting this back from sendcloud:
![Screenshot 2023-06-26 at 12 29 25](https://github.com/white-nl/commerce-sendcloud/assets/1942313/3d5a6581-cb0d-40f0-8f78-f8d69e98f080)

And actually, there *is* a field for addressLine2 which currently is sending as blank:
https://github.com/white-nl/commerce-sendcloud/blob/71754d24f57162d732c0c1ab30af05bebc4f3247/src/client/JouwWebSendcloudAdapter.php#L251

A solution could be to extract the house number from the address Craft-side, and use that instead, + send address line 2 where it should be. Only thing is I feel like the extraction logic could potentially be quite tricky...

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 4.4.14
- PHP version: 2.2.1
- Database driver & version:
- Plugins & versions: Commerce 4.2.11

**Comment by bleepsandblops** [comment]
New problem with sending addressLine2 as house_number:
`
house_number: "Ensure this field has no more than 20 characters."
`

**Comment by WHITE-developer** [comment]
Hi @bleepsandblops,
Thanks for reporting, we're going to look how we can best change this, to minimize braking changes.
Probably in combination with https://github.com/Webador/sendcloud/issues/23

**Comment by WHITE-developer** [comment]
3.0.0 is now released with the fix. Thank you for your patience.
