### ISSUE TITLE
($postalCode) must be of type string, null given

### ISSUE THREAD

**Issue by bleepsandblops** [white-nl/commerce-sendcloud#17]
### Description
It looks like for some countries, Craft doesn't ask for a postal code (in this case, UAE).

But it's required to be not null in the JouwWeb library.

On Sendcloud side, it's a bit confusing as the API says it's a 'required' field, but if you create an address manually (for the UAE) it comes up as optional.

`JouwWeb\SendCloud\Model\Address::__construct(): Argument #6 ($postalCode) must be of type string, null given, called in /home/shakespeare/www.shakespeareandcompany.com/vendor/white-nl/commerce-sendcloud/src/client/JouwWebSendcloudAdapter.php on line 254`

Solving it by doing this:
https://github.com/bleepsandblops/commerce-sendcloud/commit/22cdf4de5d476e71ca0a698e90adcb33eb1b0d81

### Steps to reproduce

1.
2.

### Additional info

- Craft version:
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by WHITE-developer** [comment]
Hey,
We'll start soon on an update to bump the `jouwweb/sendcloud` package to the latest version which will solve some problems with the addressing, as well as looking into adding some customization for the addresses

**Comment by WHITE-developer** [comment]
3.0.0 is now released with the fix. Thank you for your patience.
