### ISSUE TITLE
Sendcloud won't connect with craft 3

### ISSUE THREAD

**Issue by emmavanderhaeghen** [white-nl/commerce-sendcloud#18]
I'm having an issue with the sendcloud plugin and I'm not really getting around to it...
The integration stays on 'pending' and when I want to reconnect I keep getting this error. 

"Problems in linking
The following errors were reported while connecting to your webshop:
Your webshop gave an incorrect feedback (Callback URL). Please check your shop configuration and try again.
View error messages shops for more information"

There is no clear error message as to where exactly it goes wrong. I have a different project where I use the exact same method but in Craft 4 and so far I have not encountered any issues. I tend to believe that my issue is related to Craft 3

Some extra information about my project:

{
  "require": {
    "craftcms/cms": "3.9.6",
    "craftcms/commerce": "3.4.22.1",
    "white-nl/commerce-sendcloud": "^1.1"
  },

[Screenshot 2023-11-29 at 16 01 41](https://github.com/white-nl/commerce-sendcloud/assets/56117694/4cf0c99d-6fc7-494f-ab03-1b28e2a26597)

**Comment by WHITE-developer** [comment]
Hi @emmavanderhaeghen,
If you login to your sendcloud account and go to https://app.sendcloud.com/v2/settings/integrations/logs, you might get some more info about the connection errors

**Comment by emmavanderhaeghen** [comment]
this is the error that's logged, but the shop is live and available
  "id": 220560667,
  "base_url": "No shop url",
  "full_url": "No shop full url",
  "method": "",
  "response_code": null,
  "response": {
    "headers": {},
    "body": ""
  },
  "request": {
    "payload": null,
    "headers": {}
  },
  "created_at": "2023-11-29T01:15:33.126454+01:00",
  "exception_type": "ConnectionException",
  "exception": "Trouble to establish connection - shop is down",
  "protected": true,
  "additional_data": "",
  "formatted_date": "29-11-2023 01:15:33"
}

**Comment by WHITE-developer** [comment]
Could you check If you go to this kind of link before being redirect to `https://eu-central-1-0.app.sendcloud.com/shops/craft-commerce/authorize`

`https://panel.sendcloud.sc/shops/craft-commerce/connect/?url_webshop=https%3A%2F%2Fdemo.whiteprojects.nl%2F&webhook_url=https%3A%2F%2Fdemo.whiteprojects.nl%2Fadmin%3Fp%3Dcommerce-sendcloud%2Fwebhook%26id%3D9%26token%3Dfznaczmsvwszbsgl&shop_name=Craft%3A+Demo`

And then especially that the url_webshop and webhook_url are filled correctly, looks like these aren't getting filled correctly

**Comment by emmavanderhaeghen** [comment]
When I click the "+ register" button in Craft CMS I immediately get directed to https://eu-central-1-0.app.sendcloud.com/shops/craft-commerce/authorize 
So the url_webshop and webhook_url are probably not being filled. I just don't really understand why I am not being redirected to a similar url (https://panel.sendcloud.sc/shops/craft-commerce/connect/?url_webshop=https%3A%2F%2Fdemo.whiteprojects.nl%2F&webhook_url=https%3A%2F%2Fdemo.whiteprojects.nl%2Fadmin%3Fp%3Dcommerce-sendcloud%2Fwebhook%26id%3D9%26token%3Dfznaczmsvwszbsgl&shop_name=Craft%3A+Demo)

**Comment by WHITE-developer** [comment]
Do you have a redirect tool installed in your browser (for example https://smart.linkresearchtools.com/seo-tools/link-redirect-trace-extension?utm_campaign=link-redirect-trace&utm_content=logo&utm_source=chrome) here you should see the redirect happening

**Comment by WHITE-developer** [comment]
As we didn't hear anything anymore, I'm closing this issue, feel free to reopen if you still have issues
