### ISSUE TITLE
Returns, Sendind Statuses and Pack'n'Go

### ISSUE THREAD

**Issue by vaileamon** [white-nl/commerce-sendcloud#19]
Hi guys !

Is there any plans to go further in the integration ?

Exemples;
- Link Craft and returns processes
- Integrate Sendcloud's Pack'n'Go
- Organise returns from Craft
- Access tracking infos from Craft

Have a nice day !

**Comment by WHITE-developer** [comment]
Hi @ineghi 

A big part of these are already possible,

You can link Sendcloud status with Craft order statuses, in `/admin/commerce-sendcloud#settings-order-sync`, here you can also link the sendcloud canceled statues to your own craft order status.
If you are using Mollie as a payment gateway, you can also link it in sendcloud https://app.sendcloud.com/v2/settings/return-portal/settings, when the refund is handled in sendcloud, the payment status will automatically be updated in Craft if you are using our Mollie plugin.

The pack'n'Go feature you can use on the same way, if you map the sendcloud and craft order statuses, they will change automatically.

On the Craft order detail page, you'll find the tracking info on the right sidebar, with `craft.commercesendcloud.trackingUrl(order)` you can also get the tracking info in your frontend, as well as other things like a direct link to the return portal from sendcloud 
https://github.com/white-nl/commerce-sendcloud/blob/v3/src/variables/SendcloudVariable.php

**Comment by vaileamon** [comment]
Ok, thanks for the infos !!
Sadly, I don't use your Mollie plugin as I couldn't make the vouchers work, I had to create my own module.. But I could try to make it work the same way tho ! 
Thanks !
