### ISSUE TITLE
Test commerce sendcloud locally

### ISSUE THREAD

**Issue by princieneoshore** [white-nl/commerce-sendcloud#20]
Hi,

is it possible to test this plugin locally, on localhost, because it said that the site should be publicly accessible, but i want to test before deploying it to the server.

@WHITE-developer 
also, is there a way to register using api keys, right now, when i register, it redirect me to the sendcloud login form<

Thanks

**Comment by WHITE-developer** [comment]
Hi @princieneoshore 

To test the plugin locally you can use a service like [ngrok](https://ngrok.com/) to make your localhost public.

The plugin doesn't need an API key, when clicking register and login to sendcloud, the plugin will automatically create a connection with Sendcloud and registering the correct webhook URL's.

**Comment by princieneoshore** [comment]
@WHITE-developer 
does sendcloud have a sendbox account i can make test with ?

**Comment by WHITE-developer** [comment]
No sendcloud doesn't have a sandbox, you can best use the unstamped letter for testing
https://support.sendcloud.com/hc/en-us/articles/207948986-Can-I-create-test-labels-with-Sendcloud

**Comment by princieneoshore** [comment]
@WHITE-developer 
how to set house_number in craft,
i keep getting this error
house_number: "This field cannot be blank."

**Comment by WHITE-developer** [comment]
If the housenumber is part of the addressLine1 sendcloud will parse it automatically, if you use a custom field you can manipulate the address with this event

https://white.nl/en/craft-plugins/sendcloud/docs/

```PHP
Event::on(JouwWebSendcloudAdapter::class,
    JouwWebSendcloudAdapter::EVENT_AFTER_CREATE_ADDRESS,
    static function (AddressEvent $event): void {
        $address = $event->address;
        $shippingAddress = $event->shippingAddress;

        $address->setHouseNumber($shippingAddress->addressLine2);
        $address->setAddressLine2();
    }
);
```

**Comment by princieneoshore** [comment]
Hi @WHITE-developer 
is there a way to change the total weight of the order when pushing it to sendcloud ?
Thanks

**Comment by princieneoshore** [comment]
@WHITE-developer  is there an event before creating parcel

**Comment by WHITE-developer** [comment]
@princieneoshore 
Just added one 
```PHP
Event::on(
            JouwWebSendcloudAdapter::class,
            JouwWebSendcloudAdapter::EVENT_BEFORE_SET_PARCEL_WEIGHT,
            static function (ParcelWeightEvent $event) {
                // Parcel weight in grams
                $event->weight = 1000;
            }
        );
```

**Comment by princieneoshore** [comment]
@WHITE-developer 
hi again
i have already used something for sendcloud before using this plugin, and there are parcels already created in my sendcloud and i want to synchronise the status of these parcels to the sendcloud_ordersyncstatus table, how can i do that ?
 Because the plugin doesn't check in sendcloud if a parcel is already created before before creating one, it just check the status of sendcloud_ordersyncstatus

**Comment by princieneoshore** [comment]
@WHITE-developer

**Comment by WHITE-developer** [comment]
It should work if you add the orders/parcel manually in the `sendcloud_ordersyncstatus` table
