### ISSUE TITLE
Craft 5 support

### ISSUE THREAD

**Issue by roelvanhintum** [white-nl/commerce-sendcloud#21]
Is there plans for Craft 5 support?

**Comment by WHITE-developer** [comment]
Hi,

There are definitely plans to support Craft 5.
Can't give you an exact timeframe tho.

**Comment by jornwildenbeest** [comment]
Hi @WHITE-developer,

Any updates on this?

**Comment by white-lukas** [comment]
Just tagged `4.0.0` with commerce 5 support
