### ISSUE TITLE
Weight calculation is wrong when using grams

### ISSUE THREAD

**Issue by jornwildenbeest** [white-nl/commerce-sendcloud#24]
The following code calculates the weight in KG: 

```
private function _getOrderWeightInKg(Order $order): ?string
    {
        $weight = $order->getTotalWeight();
        if ($weight <= 0) {
            return null;
        }

        $weightUnit = Commerce::getInstance()->getSettings()->weightUnits;
        $totalWeight = match ($weightUnit) {
            'g' => $weight * 1000,
            'lb' => $weight * 0.453,
            default => $weight,
        };

        return (string)$totalWeight;
    }
```
But there is an miscalculation here.

If the weightUnit is grams (g). You want to divide by 1000, not multiply. 

Explanation: if the weight is set to 850 Gram, to get KG's you need to divide by 1000.

The fix would be: 

```
 $totalWeight = match ($weightUnit) {
            'g' => $weight / 1000,
            'lb' => $weight * 0.453,
            default => $weight,
        };
```

**Comment by white-lukas** [comment]
Hi @jornwildenbeest,
Just tagged 4.0.1 with the fix

**Comment by jornwildenbeest** [comment]
Hi @white-lukas,

Just so you know, the same bug still exists in https://github.com/white-nl/commerce-sendcloud/blob/develop-v4/src/client/SendcloudClient.php#L506

This should be changed to 
```
'g' => $weight / 1000,
'lb' => $weight * 0.453,
 default => $weight,
``` 

as well.
