### ISSUE TITLE
Support for PO box numbers in Germany

### ISSUE THREAD

**Issue by rbrv** [white-nl/commerce-sendcloud#25]
Hi! Is there support for sending PO box numbers when sending using e.g. DHL?

![Screenshot_2024](https://github.com/user-attachments/assets/da5d4f41-9444-4bb6-aae5-232be63d4946)

**Comment by white-lukas** [comment]
Hi @rbrv,

The filled in PO box number should be part of the  response that is captured inside [here](https://github.com/white-nl/commerce-sendcloud/blob/develop-v4/src/models/OrderSyncStatus.php#L46)  

And you can add it the the parcel data by hooking int the `EVENT_BEFORE_PUSH_PARCEL` event.
(not sure about the key how the PO box number is added to the servicePoint.)

```PHP
Event::on(
            SendcloudClient::class,
            SendcloudClient::EVENT_BEFORE_PUSH_PARCEL,
            static function(ParcelEvent $event): void {
                $parcel = $event->parcel;
                $order = $event->order;

                $orderSyncStatus = SendcloudPlugin::getInstance()->orderSync->getOrderSyncStatusByOrderId($order->id);
                $servicePoint = $orderSyncStatus->servicePoint;
                if ($servicePoint !== null) {
                    $poNumber = $servicePoint['poBoxNumber'] ?? null;
                    if ($poNumber) {
                        $parcel->setToPostNumber($poNumber);
                    }
                }
            }
        );
```

**Comment by rbrv** [comment]
Ah perfect, thank you!

**Comment by nikolenko-dmitriy** [comment]
> Hi @rbrv,
> 
> The filled in PO box number should be part of the response that is captured inside [here](https://github.com/white-nl/commerce-sendcloud/blob/develop-v4/src/models/OrderSyncStatus.php#L46)
> 
> And you can add it the the parcel data by hooking int the `EVENT_BEFORE_PUSH_PARCEL` event. (not sure about the key how the PO box number is added to the servicePoint.)
> 
> ```
> Event::on(
>             SendcloudClient::class,
>             SendcloudClient::EVENT_BEFORE_PUSH_PARCEL,
>             static function(ParcelEvent $event): void {
>                 $parcel = $event->parcel;
>                 $order = $event->order;
> 
>                 $orderSyncStatus = SendcloudPlugin::getInstance()->orderSync->getOrderSyncStatusByOrderId($order->id);
>                 $servicePoint = $orderSyncStatus->servicePoint;
>                 if ($servicePoint !== null) {
>                     $poNumber = $servicePoint['poBoxNumber'] ?? null;
>                     if ($poNumber) {
>                         $parcel->setToPostNumber($poNumber);
>                     }
>                 }
>             }
>         );
> ```

Hi! Are you sure that this example could work? I can't find event `SendcloudClient::EVENT_BEFORE_PUSH_PARCEL`. Here is the full list of plugin events that could be used for hooking data:

<img width="617" alt="Screen Shot 2024-12-06 в 14 28 50" src="https://github.com/user-attachments/assets/2d989191-b855-4c54-b49a-9ec81645ad6a">

**Comment by white-lukas** [comment]
Hi @nikolenko-dmitriy,

The example code is for the 4.x version, in earlier versions this event didn't exist yet

**Comment by nikolenko-dmitriy** [comment]
@white-lukas yes, I see. I tried to test it on `Craft CMS 4.x` version where `Sendcloud 3.x` version is available only. Thank you for the response!
