### ISSUE TITLE
Address3 -> Housenumber addition

### ISSUE THREAD

**Issue by Floriswijgergangs** [white-nl/commerce-sendcloud#4]
Hi, we are testing with the addresses, the address3 is not set as a addition to the housenumber. 
Our checkout has a separate housenumber and housenumber addition field, in Sendcloud it's one housenumber field.
Is it possible to extend the housenumber from address2 to address2 + address3?

**Comment by WHITE-developer** [comment]
Hello, Sorry for the late response. We will take your request into consideration and keep you informed.

**Comment by WHITE-developer** [comment]
This is fixed in version 1.0.5.
