### ISSUE TITLE
carriers

### ISSUE THREAD

**Issue by wmdhosting** [white-nl/commerce-sendcloud#7]
Im from EU. .

PLugin seems great :)

As much i see most of carriers are avaible only in few EU countries.. 

DHL, DPD; GLS:...

I suupose need to contact directly Sendcloud.  to  enable same in new countries or adding new one..

**Comment by WHITE-developer** [comment]
Hi @wmdhosting,

You are right, the list of available carriers is controlled by Sendcloud. You have to contact them to enable or add new carriers in certain countries.

**Comment by wmdhosting** [comment]
Seems  they dont have plans to add carriers fast.. 

I found this EU service  https://www.eurosender.com/ 

Seems they cover everything...   and  all countries..

Any plans on your side to add some other provider beside sendcloud

**Comment by WHITE-developer** [comment]
Hi @wmdhosting ,
This plugin is created in close cooperation with Sendcloud, so we won't be adding other providers besides Sendcloud

**Comment by wmdhosting** [comment]
OK thx for info.. 

Do you have any other commerce plugins in plans :)

Have seen you done Connector thing.. that sounds very interesting :)
